[package]
name = "AMMPractice"
version = "0.0.0"

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
AMMPractice= "_"

[dev-addresses]
AMMPractice="0x2"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "d334ea3c4ff02924fd8726d1974d6f08011d3239" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "d334ea3c4ff02924fd8726d1974d6f08011d3239" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "d334ea3c4ff02924fd8726d1974d6f08011d3239" }